# Generated by Django 4.2.4 on 2023-08-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_photo_latitude_photo_longitude_photo_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
