# Generated by Django 4.2.4 on 2023-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date',
            new_name='date_uploaded',
        ),
        migrations.AddField(
            model_name='photo',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='make',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='model',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='orientation',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='resolution_unit',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='street',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='x_resolution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='y_resolution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
