# Generated by Django 4.2.4 on 2023-08-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_date_photo_date_uploaded_photo_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='county',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
