# Generated by Django 4.2.4 on 2023-08-13 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_album_photos_user_albums"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="user",
        ),
    ]
