# Generated by Django 4.2.4 on 2024-07-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_photo_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='test',
        ),
    ]
